#!/bin/sh
set -e
set -o nounset
set -o pipefail

usage() {
  echo "usage: $0 source_subvolume subvolume_relative"
  echo "       source_subvolume is the source of the snapshot"
  echo "       subvolume_relative is the path of the source_subvolume relative to the mount root"
  echo "example for a filesystem mounted to /mnt, deleting /mnt/backup/root: $0 /mnt/root backup/root"
}

script="$0"
src="$1"
snappath="$2"

btrfs subvolume list -o "$src" |awk '{print $9}' | sed "s,^${snappath}/,,g" | \
  while read sub; do
    "$script" "$src"/"$sub" "$snappath"/"$sub"
    btrfs sub del "$src"/"$sub"
  done
